{
  'output_directory': '.\LasVegas',                         # Where to save the output files
  'boundary_file': '.\configs\LasVegas\boundary.kml',       # Input kml file setting the boundary of the map to create
  'zoom_factor': 0.02,                                      # [0: maximum zoom in (things look very big), 1: maximum zoom out (things look very small)] 
  'geo_width': 1.14
}