{
  'output_directory': '.\Syria',                                # Where to save the output files
  'boundary_file': '.\configs\Syria\MediumResolution.kml',      # Input kml file setting the boundary of the map to create
  'zoom_factor': 0.25                                           # [0: maximum zoom in (things look very big), 1: maximum zoom out (things look very small)] 
}