name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client:
    name: Client (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 20.x
        os:
          - ubuntu-20.04
          - windows-2019
        include:
          - os: ubuntu-20.04
            script: build-release-linux
          - os: windows-2019
            script: build-release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build
        working-directory: client
        run: npm run ${{ matrix.script }}
